# Generated by Django 5.1.3 on 2024-11-21 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolarMX2HeartRateDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eui', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fw', models.CharField(max_length=10)),
                ('pulse', models.FloatField()),
                ('fraud', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamsungBPABloodPressureDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eui', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=10)),
                ('bp_sys', models.PositiveSmallIntegerField()),
                ('bp_dia', models.PositiveSmallIntegerField()),
                ('fraud', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamsungX1SHeartRateDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eui', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=10)),
                ('hr', models.PositiveSmallIntegerField()),
                ('fraud', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
